--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CloudMinePE/AMySQL
build-by-default: true
branches:
  - master
projects:
  amysqlo:
    type: library
    model: virion
    path: ""
    libs:
      - src: CloudMinePE/MySQLO/mysqlo
        version: ^0.1.0
...
